version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "9000:80"
        depends_on:
            - php
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached

    php:
        image: php:7-fpm
        volumes:
            - "./app:/app"

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql:cached
            - ./mysql/conf:/etc/mysql/conf.d:cached
        environment:
            - MYSQL_ROOT_PASSWORD=password
        command: --innodb-use-native-aio=0

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        depends_on:
            - mysql
        ports:
            - 9001:80
