version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"

    php:
        image: php:7-fpm
        volumes:
            - "./app:/app"

    mysql:
        image: mysql:5.7
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/conf:/etc/mysql/conf.d"
        environment:
            - MYSQL_ROOT_PASSWORD=password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        depends_on:
            - mysql
        ports:
            - 8080:80
        volumes:
            - "./phpmyadmin/sessions:/sessions"
